name: PyVCG CI Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        py-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/cvc5/cvc5/releases/download/cvc5-1.0.8/cvc5-Linux'
          name: 'cvc5'
          version: '1.0.8'
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.py-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          coverage run --branch --rcfile=coverage.cfg -m unittest discover -s tests -v
          coverage report --rcfile=coverage.cfg --fail-under=100
